---
name: test-network-org2
version: 1.0.0
client:
  organization: Org2
  connection:
    timeout:
      peer:
        endorser: '300'
organizations:
  Org2:
    mspid: Org2MSP
    peers:
    - peer0.org2.example.com
    certificateAuthorities:
    - ca.org2.example.com
peers:
  peer0.org2.example.com:
    url: grpcs://localhost:9051
    tlsCACerts:
      pem: |
          -----BEGIN CERTIFICATE-----
          MIICVzCCAf6gAwIBAgIRAIc/klAFsn03J9WmtpY5TRQwCgYIKoZIzj0EAwIwdjEL
          MAkGA1UEBhMCVVMxEzARBgNVBAgTCkNhbGlmb3JuaWExFjAUBgNVBAcTDVNhbiBG
          cmFuY2lzY28xGTAXBgNVBAoTEG9yZzIuZXhhbXBsZS5jb20xHzAdBgNVBAMTFnRs
          c2NhLm9yZzIuZXhhbXBsZS5jb20wHhcNMjUwNTA2MDcyMzAwWhcNMzUwNTA0MDcy
          MzAwWjB2MQswCQYDVQQGEwJVUzETMBEGA1UECBMKQ2FsaWZvcm5pYTEWMBQGA1UE
          BxMNU2FuIEZyYW5jaXNjbzEZMBcGA1UEChMQb3JnMi5leGFtcGxlLmNvbTEfMB0G
          A1UEAxMWdGxzY2Eub3JnMi5leGFtcGxlLmNvbTBZMBMGByqGSM49AgEGCCqGSM49
          AwEHA0IABMnqkA3+1FbjsMN6diJ8FQ5l0BxlYjFCKJO+LvR+OHue7x51Td2MH1jf
          OiMHz0HifMu9C4K+drOjyzjle1Te03OjbTBrMA4GA1UdDwEB/wQEAwIBpjAdBgNV
          HSUEFjAUBggrBgEFBQcDAgYIKwYBBQUHAwEwDwYDVR0TAQH/BAUwAwEB/zApBgNV
          HQ4EIgQgj9qthoxEI7k6bqnHLL4L6cMVbHzDJVQOecD7w9oYxSowCgYIKoZIzj0E
          AwIDRwAwRAIgHdXlggMiRpfRjep4laQp2H87neeFn3nlImFSucYzM3MCIALHhHpm
          4TByuepgHvkmEpeARdiBjdAirAWruWjBybZc
          -----END CERTIFICATE-----
          
    grpcOptions:
      ssl-target-name-override: peer0.org2.example.com
      hostnameOverride: peer0.org2.example.com
certificateAuthorities:
  ca.org2.example.com:
    url: https://localhost:8054
    caName: ca-org2
    tlsCACerts:
      pem: 
        - |
          -----BEGIN CERTIFICATE-----
          MIICUTCCAfegAwIBAgIQXIsGVGLPJ5NI/oQkQPeabTAKBggqhkjOPQQDAjBzMQsw
          CQYDVQQGEwJVUzETMBEGA1UECBMKQ2FsaWZvcm5pYTEWMBQGA1UEBxMNU2FuIEZy
          YW5jaXNjbzEZMBcGA1UEChMQb3JnMi5leGFtcGxlLmNvbTEcMBoGA1UEAxMTY2Eu
          b3JnMi5leGFtcGxlLmNvbTAeFw0yNTA1MDYwNzIzMDBaFw0zNTA1MDQwNzIzMDBa
          MHMxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpDYWxpZm9ybmlhMRYwFAYDVQQHEw1T
          YW4gRnJhbmNpc2NvMRkwFwYDVQQKExBvcmcyLmV4YW1wbGUuY29tMRwwGgYDVQQD
          ExNjYS5vcmcyLmV4YW1wbGUuY29tMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE
          thrTdPnC2Lx/5msljwuFsw90FrfYcQE77z+ni289cIPU87rKOVJEa/hrcf57zk1W
          qNRBBmF9cvH+ikazuBCLK6NtMGswDgYDVR0PAQH/BAQDAgGmMB0GA1UdJQQWMBQG
          CCsGAQUFBwMCBggrBgEFBQcDATAPBgNVHRMBAf8EBTADAQH/MCkGA1UdDgQiBCB7
          /r3UZZWhOPJK/9RsQs1Yu3ezNpF5T7Uo7FCM2zhSzzAKBggqhkjOPQQDAgNIADBF
          AiEAlmUAhkmUiLTZLXrOfPPE3eHxeYrOlS+bMy7id19ogasCIExyVfrCt5Ojvh/d
          F+WgXHgXO5AODMYQtYlbrAXcmAzV
          -----END CERTIFICATE-----
          
    httpOptions:
      verify: false
